apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-argocd
  name: nginx-argocd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-argocd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-argocd
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
